language: node_js
node_js:
- '6'
cache: yarn
deploy:
  provider: npm
  email: apstukalin@gmail.com
  api_key:
    secure: FBAg/y7NBYVo037+RXg5iGasw7zv4nRzl5pLUNs4idUyI8Zi+78hzIgBOpSNLvWQpMmHKYtL/YtleOVjTy2pIsHP9lQljmJjxALsqdd8KCUAShs/sbDiHRO//T3h5DmbfJ0yR+4aDkFfuQlIdddhMm4lgwXXFm4t8HMwtF6ReK7mCu1CqXWge/GmWgFrnV68kX8FPzXHTV5hZwcVF+gh5NRjnZU+yySWJhUm+D+k0BwitAJxLoYKIGFXUey4uFDm7HNVxC9IS2P8sm9PhRhYNqOMozcDC8ku2HNANF2DLB4DT7DHlL7yMIA7wKI1g7QzzDx98CqFJGAwgZLujOtxSgZ6uEE7rzhx9FEB8hLmHANP9rjSD4yxy/nLeghNoncds/AYrYA1lc9DpX+aCR2Ll/uW51/RqrhmiKGAsDNdXopFJ764riRPpBEwhdobbd6G6ZFel41gl6Od8IaPrKLMfAzhWkyIdQX9JPiGHq//M0n37IsYndp1gSC0lL9f4Hur2dbDL81iipCLi8AedqEMMFnQLBN5M/ect7V0cd7OR1cahH4kCqNgJvzF0+lQj6RCUNBqX3xzi7VmZRk/WlGdz1mn/nx/5DvzWyFkTV6H2VVqI+OR/2LGi4lcr169Rv5sf4e36sHDt9ks0RUMxcz9v0l9YWMTjL2cbHgcfTtpV2U=
  on:
    tags: true
    repo: HospitalRun/hospitalrun-dblisteners
